# Generated by Django 6.0.3 on 2026-03-11 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_shikomori', models.CharField(max_length=255, unique=True)),
                ('pos', models.CharField(choices=[('nom', 'Nom'), ('verbe', 'Verbe'), ('adj', 'Adjectif'), ('adv', 'Adverbe'), ('pron', 'Pronom'), ('prep', 'Préposition'), ('conj', 'Conjonction'), ('interj', 'Interjection')], max_length=50, verbose_name='Partie du discours')),
                ('phonetics', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_term', models.CharField(max_length=255)),
                ('proposed_translation', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning_fr', models.TextField()),
                ('dialect', models.CharField(choices=[('grand_comore', 'Shingazidja (Grande Comore)'), ('anjouan', 'Shindzuani (Anjouan)'), ('moheli', 'Shimwali (Mohéli)'), ('mayotte', 'Shimaore (Mayotte)'), ('standard', 'Standard')], default='standard', max_length=50)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='linguistics.word')),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_shikomori', models.TextField()),
                ('sentence_fr', models.TextField()),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='linguistics.word')),
            ],
        ),
    ]
